title: Anton Hlushkov's Website
description: >-
  Just another publicist website.
baseurl: ""
url: "https://antonhlushkov.github.io"
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - index.md
custom_css:
  - /assets/css/custom.css
minima:
  social_links:
    - title: LinkedIn
      icon: linkedin
      url: "https://linkedin.com/in/anton-hlushkov"
    - title: X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/antonhlushkov"
