title: Anton Hlushkov's Website
description: >-
  Just another publicist website.
baseurl: ""
url: "https://antonhlushkov.github.io"

theme: minima

plugins:
  - jekyll-feed

minima:
  skin: dark
  show_excerpts: true
  social_links:
    - platform: linkedin
      user_url: "https://linkedin.com/in/anton-hlushkov"
    - platform: twitter
      user_url: "https://x.com/antonhlushkov"
      title: X (formerly Twitter)