title: Anton Hlushkov's Website
author:
  name: Anton Hlushkov

description: Personal website of Anton Hlushkov.

baseurl: ""
url: "https://antonhlushkov.github.io"

custom_css: /assets/css/style.scss

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag



 